name: Build Go Project

on:
  push:
    branches:
      - "**"
  workflow_dispatch: # Allows manual triggering

env:
  APP_NAME: N_m3u8DL-RE-GO
  VERSION_TAG: v0.1.0

jobs:
  build-desktop:
    name: Build for ${{ matrix.goos }}/${{ matrix.goarch }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [windows, linux, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goos: darwin
            goarch: arm64
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
      - name: Set up build variables
        id: vars
        run: |
          DATE=$(date -u -d '8 hours' +'%Y%m%d')
          SHA_SHORT=$(git rev-parse --short HEAD)
          PLATFORM_ARCH="${{ matrix.goos }}-${{ matrix.goarch }}"
          FULL_NAME_BASE="${{ env.APP_NAME }}_${{ env.VERSION_TAG }}_${PLATFORM_ARCH}_${DATE}_${SHA_SHORT}"
          FULL_EXE_NAME="${FULL_NAME_BASE}${{ matrix.goos == 'windows' && '.exe' || '' }}"
          # Simplified archive name for the outer zip
          ARCHIVE_NAME_NO_EXT="${PLATFORM_ARCH}"
          FINAL_ARCHIVE_NAME_WITH_EXT="${ARCHIVE_NAME_NO_EXT}.zip"

          echo "full_exe_name=${FULL_EXE_NAME}" >> $GITHUB_OUTPUT
          echo "archive_name_no_ext=${ARCHIVE_NAME_NO_EXT}" >> $GITHUB_OUTPUT
          echo "final_archive_name_with_ext=${FINAL_ARCHIVE_NAME_WITH_EXT}" >> $GITHUB_OUTPUT
          echo "platform_arch=${PLATFORM_ARCH}" >> $GITHUB_OUTPUT
      - name: Build application
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: 0
        run: |
          go build -v -trimpath -o "dist/${{ steps.vars.outputs.full_exe_name }}" .
      - name: Package application
        id: package
        run: |
          cd dist
          if [ "${{ matrix.goos }}" == "windows" ]; then
            zip "${{ steps.vars.outputs.final_archive_name_with_ext }}" "${{ steps.vars.outputs.full_exe_name }}"
          else
            # For non-Windows, first create a tar.gz of the executable
            tar -czvf "${{ steps.vars.outputs.full_exe_name }}.tar.gz" "${{ steps.vars.outputs.full_exe_name }}"
            # Then zip that tar.gz
            zip "${{ steps.vars.outputs.final_archive_name_with_ext }}" "${{ steps.vars.outputs.full_exe_name }}.tar.gz"
          fi
          echo "asset_path=${{ steps.vars.outputs.final_archive_name_with_ext }}" >> $GITHUB_OUTPUT
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.package.outputs.asset_path }} # This will be platform-arch.zip
          path: dist/${{ steps.package.outputs.asset_path }}
          retention-days: 7

  build-macos-arm64:
    name: Build for darwin/arm64
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
      - name: Set up build variables
        id: vars
        run: |
          DATE=$(date -u -v+8H +'%Y%m%d') # macOS specific date command
          SHA_SHORT=$(git rev-parse --short HEAD)
          PLATFORM_ARCH="darwin-arm64"
          FULL_NAME_BASE="${{ env.APP_NAME }}_${{ env.VERSION_TAG }}_${PLATFORM_ARCH}_${DATE}_${SHA_SHORT}"
          FULL_EXE_NAME="${FULL_NAME_BASE}" # No .exe for macOS
          ARCHIVE_NAME_NO_EXT="${PLATFORM_ARCH}"
          FINAL_ARCHIVE_NAME_WITH_EXT="${ARCHIVE_NAME_NO_EXT}.zip"

          echo "full_exe_name=${FULL_EXE_NAME}" >> $GITHUB_OUTPUT
          echo "archive_name_no_ext=${ARCHIVE_NAME_NO_EXT}" >> $GITHUB_OUTPUT
          echo "final_archive_name_with_ext=${FINAL_ARCHIVE_NAME_WITH_EXT}" >> $GITHUB_OUTPUT
          echo "platform_arch=${PLATFORM_ARCH}" >> $GITHUB_OUTPUT
      - name: Build application
        env:
          GOOS: darwin
          GOARCH: arm64
          CGO_ENABLED: 0
        run: |
          go build -v -trimpath -o "dist/${{ steps.vars.outputs.full_exe_name }}" .
      - name: Package application
        id: package
        run: |
          cd dist
          # First create a tar.gz of the executable
          tar -czvf "${{ steps.vars.outputs.full_exe_name }}.tar.gz" "${{ steps.vars.outputs.full_exe_name }}"
          # Then zip that tar.gz
          zip "${{ steps.vars.outputs.final_archive_name_with_ext }}" "${{ steps.vars.outputs.full_exe_name }}.tar.gz"
          echo "asset_path=${{ steps.vars.outputs.final_archive_name_with_ext }}" >> $GITHUB_OUTPUT
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.package.outputs.asset_path }} # This will be darwin-arm64.zip
          path: dist/${{ steps.package.outputs.asset_path }}
          retention-days: 7

  build-android:
    name: Build for android/${{ matrix.goarch }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goarch: [amd64, arm64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
      - name: Set up Android NDK r25b
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r25b-linux.zip -O ndk.zip
          unzip -q ndk.zip
          echo "NDK_HOME=$PWD/android-ndk-r25b" >> $GITHUB_ENV
      - name: Set up build variables
        id: vars
        run: |
          DATE=$(date -u -d '8 hours' +'%Y%m%d')
          SHA_SHORT=$(git rev-parse --short HEAD)
          PLATFORM_ARCH="android-${{ matrix.goarch }}"
          FULL_NAME_BASE="${{ env.APP_NAME }}_${{ env.VERSION_TAG }}_${PLATFORM_ARCH}_${DATE}_${SHA_SHORT}"
          FULL_EXE_NAME="${FULL_NAME_BASE}" # No .exe for Android
          ARCHIVE_NAME_NO_EXT="${PLATFORM_ARCH}"
          FINAL_ARCHIVE_NAME_WITH_EXT="${ARCHIVE_NAME_NO_EXT}.zip"

          echo "full_exe_name=${FULL_EXE_NAME}" >> $GITHUB_OUTPUT
          echo "archive_name_no_ext=${ARCHIVE_NAME_NO_EXT}" >> $GITHUB_OUTPUT
          echo "final_archive_name_with_ext=${FINAL_ARCHIVE_NAME_WITH_EXT}" >> $GITHUB_OUTPUT
          echo "platform_arch=${PLATFORM_ARCH}" >> $GITHUB_OUTPUT

          if [ "${{ matrix.goarch }}" == "arm64" ]; then
            TOOLCHAIN_PREFIX="aarch64-linux-android"
          else
            TOOLCHAIN_PREFIX="x86_64-linux-android"
          fi
          echo "CC=${NDK_HOME}/toolchains/llvm/prebuilt/linux-x86_64/bin/${TOOLCHAIN_PREFIX}29-clang" >> $GITHUB_ENV
          echo "CXX=${NDK_HOME}/toolchains/llvm/prebuilt/linux-x86_64/bin/${TOOLCHAIN_PREFIX}29-clang++" >> $GITHUB_ENV
      - name: Build application
        env:
          GOOS: android
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: 1
        run: |
          go build -v -trimpath -ldflags "-w -s -extldflags '-Wl,--hash-style=sysv'" -o "dist/${{ steps.vars.outputs.full_exe_name }}" .
      - name: Package application
        id: package
        run: |
          cd dist
          # First create a tar.gz of the executable
          tar -czvf "${{ steps.vars.outputs.full_exe_name }}.tar.gz" "${{ steps.vars.outputs.full_exe_name }}"
          # Then zip that tar.gz
          zip "${{ steps.vars.outputs.final_archive_name_with_ext }}" "${{ steps.vars.outputs.full_exe_name }}.tar.gz"
          echo "asset_path=${{ steps.vars.outputs.final_archive_name_with_ext }}" >> $GITHUB_OUTPUT
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.package.outputs.asset_path }} # This will be android-goarch.zip
          path: dist/${{ steps.package.outputs.asset_path }}
          retention-days: 7